"""empty message

Revision ID: 6d7bdc8feed2
Revises: baca777124f1
Create Date: 2020-01-12 08:56:35.147822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7bdc8feed2'
down_revision = 'baca777124f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    # ### end Alembic commands ###
