"""empty message

Revision ID: 790ee7514122
Revises: 75a5649ae6a7
Create Date: 2020-01-14 23:07:30.453450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790ee7514122'
down_revision = '75a5649ae6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['modifiedquestion.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('link')
    # ### end Alembic commands ###
