"""empty message

Revision ID: c7e5725016b0
Revises: db715e88735b
Create Date: 2020-01-23 05:19:06.139422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e5725016b0'
down_revision = 'db715e88735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifiedquestion', sa.Column('user_email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_modifiedquestion_user_email'), 'modifiedquestion', ['user_email'], unique=False)
    op.add_column('rawquestion', sa.Column('user_email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_rawquestion_user_email'), 'rawquestion', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rawquestion_user_email'), table_name='rawquestion')
    op.drop_column('rawquestion', 'user_email')
    op.drop_index(op.f('ix_modifiedquestion_user_email'), table_name='modifiedquestion')
    op.drop_column('modifiedquestion', 'user_email')
    # ### end Alembic commands ###
