"""empty message

Revision ID: d83b0893fe29
Revises: 790ee7514122
Create Date: 2020-01-14 23:39:43.290157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b0893fe29'
down_revision = '790ee7514122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifiedquestion', sa.Column('answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modifiedquestion', 'answer')
    # ### end Alembic commands ###
