"""empty message

Revision ID: db715e88735b
Revises: db44ae5b08f0
Create Date: 2020-01-20 10:40:27.474817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db715e88735b'
down_revision = 'db44ae5b08f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modifiedquestion") as batch_op:
        batch_op.drop_column('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifiedquestion', sa.Column('likes', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
